name: amplicon-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - trim-galore=0.6.6
  - ea-utils=1.1.2.779
  - bowtie2=2.4.2
  - bamtools=2.5.1
  - seqkit=0.15.0
  - samtools=1.11
  - bbmap=38.90
  - muscle=3.8.1551
  - bfc
  - picard=2.25.0
  - multiqc=1.9
  - preseq=2.0.3
  - pip
  - pip:
    - cogent3
    - seaborn
    - biopython
    - pandas
