name: amplicon-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - trim-galore=0.6.2
  - ea-utils=1.1.2.779
  - bowtie2=2.4.1
  - seqkit=0.13.2
  - samtools=1.10
  - bbmap=38.86
