name: amplicon-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - trim-galore
  - ea-utils
  - bowtie2
  - bamtools
  - seqkit
  - samtools
  - bbmap
  - muscle
  - bfc
  - picard
  - multiqc
  - pip
  - pip:
    - cogent3
    - seaborn
    - biopython
    - pandas
